Repository sunflower-land/sunflower-land, pull requests merged in 2022-04, with the labels that each got.

#471 [FEAT] Crop Rewards
  src/assets/npcs/synced.gif
  src/features/crops/components/CropReward.tsx
  src/features/crops/components/Field.tsx
  src/features/game/components/Success.tsx
  src/features/game/events/harvest.ts
  src/features/game/events/index.ts
  src/features/game/events/rewarded.ts
  src/features/game/lib/transforms.ts
  src/features/game/types/game.ts
Labels: enhancement

#479 [FEAT] UI Touchups
  src/assets/npcs/team.png
  src/assets/resources/gold/gold_drop.png
  src/assets/resources/gold/gold_empty.png
  src/assets/resources/gold/gold_spark.png
  src/assets/resources/iron/iron_dropped.png
  src/assets/resources/iron/iron_empty.png
  src/assets/resources/iron/iron_spark.png
  src/assets/resources/stone/stone_drop.png
  src/assets/resources/stone/stone_empty.png
  src/assets/resources/stone/stone_spark.png
  src/features/auth/components/ConnectingError.tsx
  src/features/auth/useImagePreloader.tsx
  src/features/crops/components/CropZoneFour.tsx
  src/features/crops/components/CropZoneThree.tsx
  src/features/crops/components/CropZoneTwo.tsx
  src/features/crops/components/Field.tsx
  src/features/game/events/rewarded.ts
  src/features/game/lib/constants.ts
  src/features/game/lib/gameMachine.ts
  src/features/quarry/components/Iron.tsx
  src/features/teamDonation/TeamDonation.tsx
Labels: enhancement

#496 [FEAT] Oracle Wishing Well
  .env.sample
  .github/workflows/testnet.yml
  src/features/wishingWell/actions/collectFromWell.ts
  src/features/wishingWell/actions/loadWishingWell.ts
  src/features/wishingWell/components/WishingWellModal.tsx
  src/features/wishingWell/wishingWellMachine.ts
  src/lib/blockchain/WishingWell.ts
  src/lib/blockchain/abis/WishingWell.json
Labels: enhancement

#490 [FEAT] Banking Withdraw Split Modal
  src/features/bank/components/Withdraw.tsx
  src/features/bank/components/WithdrawItems.tsx
  src/features/bank/components/WithdrawTokens.tsx
  src/features/game/actions/sync.ts
  src/features/game/actions/withdraw.ts
  src/features/game/components/Success.tsx
Labels: enhancement

#499 [FEAT] Bank improvements
  src/components/ui/Box.tsx
  src/features/bank/components/Withdraw.tsx
  src/features/bank/components/WithdrawItems.tsx
  src/features/bank/components/WithdrawTokens.tsx
  src/features/bank/lib/bankUtils.ts
  src/features/game/actions/visit.ts
  src/features/game/lib/constants.ts
  src/features/game/lib/gameMachine.ts
Labels: enhancement

#550 [FEAT] Mint Cooldown
  src/features/bank/components/Withdraw.tsx
  src/features/blacksmith/components/Rare.tsx
  src/features/blacksmith/lib/mintUtils.ts
  src/features/game/actions/loadSession.ts
  src/features/game/lib/gameMachine.ts
  src/features/tailor/components/TailorSale.tsx
Labels: enhancement

#613 [FEAT] Animated Beavers
  src/assets/nfts/apprentice_beaver.gif
  src/assets/nfts/apprentice_beaver.png
  src/assets/nfts/beaver.gif
  src/assets/nfts/beaver.png
  src/assets/nfts/construction_beaver.gif
  src/assets/nfts/construction_beaver.png
  src/features/game/components/Decorations.tsx
  src/features/game/types/images.ts
Labels: enhancement

#640 [FEAT] add close icon to modals
  src/features/crops/components/CropZoneFour.tsx
  src/features/crops/components/CropZoneTwo.tsx
  src/features/crops/components/WheatGoblin.tsx
  src/features/forest/components/Lumberjack.tsx
  src/features/game/components/Lore.tsx
  src/features/game/expansion/ExpansionInfo.tsx
  src/features/water/components/Frog.tsx
Labels: ⭐ feature

#641 [CHORE] Minor Types & Gramma adjustments for readme
  README.md
Labels: 📝 documentation, ⚙️ chore

#685 [FEAT] Buy remaining seed stock button when less than 10 remaining
  src/features/crops/components/Seeds.tsx
  src/features/crops/lib/makeBulkSeedBuyAmount.ts
  src/features/crops/lib/makeBulkSeedByAmount.test.ts
Labels: ⭐ feature, 📱 ux/ui

#694 [FIX] kbd (up, down, left and right) were working when any modal is open
  src/features/game/lib/mapMovement.ts
Labels: 🐞 bug

#681 [FEAT] Show current release version tag on splash screen
  .env.sample
  .github/workflows/mainnet.yml
  .github/workflows/testnet.yml
  src/features/auth/components/Splash.tsx
  src/lib/config.ts
Labels: ⭐ feature, 📱 ux/ui

#679 [CHORE] Resolve linting warnings for hooks and unused imports
  .eslintrc.js
  .github/workflows/ci.yml
  _scripts/erc1155Metadata.ts
  package.json
  src/Navigation.tsx
  src/components/animation/SpriteAnimator.tsx
  src/components/ui/Action.tsx
  src/components/ui/TimeLeftPanel.tsx
  src/features/animals/components/Chickens.tsx
  src/features/auth/Auth.tsx
  src/features/auth/components/CreateFarm.tsx
  src/features/auth/components/SupplyReached.tsx
  src/features/auth/components/TooManyRequests.tsx
  src/features/bakery/components/CraftingItems.tsx
  src/features/bank/lib/bankUtils.ts
  src/features/blacksmith/components/CraftingItems.tsx
  src/features/crops/components/Field.tsx
  src/features/crops/components/Plants.tsx
  src/features/crops/components/Seeds.tsx
  src/features/crops/components/Soil.tsx
  src/features/crops/components/WheatGoblin.tsx
  src/features/forest/components/Tree.tsx
  src/features/game/Game.tsx
  src/features/game/GameProvider.tsx
  src/features/game/actions/loadSession.ts
  src/features/game/components/Blacklisted.tsx
  src/features/game/components/Decorations.tsx
  src/features/game/events/craft.ts
  src/features/game/events/goldMine.ts
  src/features/game/lib/transforms.ts
  src/features/house/House.tsx
  src/features/hud/Hud.tsx
  src/features/hud/components/Inventory.tsx
  src/features/hud/components/InventoryTabContent.tsx
  src/features/hud/components/Menu.tsx
  src/features/hud/components/Settings.tsx
  src/features/hud/components/howToPlay/HowToModalHeader.tsx
  src/features/hud/components/howToPlay/HowToPlay.tsx
  src/features/hud/lib/onboarding.ts
  src/features/wishingWell/components/WishingWellModal.tsx
  src/lib/blockchain/Farm.ts
  src/lib/blockchain/Inventory.ts
  src/lib/blockchain/SunflowerFarmers.ts
  src/lib/blockchain/Token.ts
  src/lib/blockchain/WishingWell.ts
  vite.config.ts
  yarn.lock
Labels: ⚙️ chore
