Repository sunflower-land/sunflower-land, pull requests merged in 2024-08, with the labels that each got.

#4151 [FIX] Digby Default Tab
  src/features/world/scenes/BeachScene.ts
  src/features/world/ui/beach/Digby.tsx
Labels: 🐞 Bug

#4152 [FEAT] Reveling Lemon and Lemon Frog Boosts
  src/features/game/events/landExpansion/fruitHarvested.test.ts
  src/features/game/events/landExpansion/fruitHarvested.ts
  src/features/game/events/landExpansion/fruitPlanted.test.ts
  src/features/game/events/landExpansion/fruitPlanted.ts
  src/features/game/types/collectibleItemBuffs.ts
  src/features/game/types/removeables.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4158 [FEAT] Fix Drill Bug
  src/features/world/scenes/BeachScene.ts
Labels: 🐞 Bug

#3853 [FEAT] Chinese Fonts
  index.html
  src/components/ui/ProgressBar.tsx
  src/features/game/expansion/components/Pontoon.tsx
  src/features/island/hud/components/settings-menu/general-settings/FontSettings.tsx
  src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
  src/features/world/ui/deliveries/BumpkinDelivery.tsx
  src/lib/utils/fonts.ts
  src/styles.css
  tailwind.config.js
Labels: 🌐 Language

#4178 [CHORE] Trading Board Buy Panel Improvements
  src/features/world/ui/npcs/TradingBoard.tsx
  src/features/world/ui/trader/BuyPanel.tsx
Labels: ⚙️ Chore
