Repository sunflower-land/sunflower-land, pull requests merged in 2024-07, with the labels that each got.

#4002 [FIX] Unwanted collisions in map
  src/assets/map/beach.json
  src/assets/map/plaza.json
  src/features/world/scenes/BaseScene.ts
Labels: 🐞 bug

#4029 [FEAT] Add Inventory Amount in Buy Screen
  src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
  src/features/world/ui/trader/BuyPanel.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: 📱 ux/ui

#4019 [CHORE] Add custom number input component
  src/components/ui/BulkSellModal.tsx
  src/components/ui/NumberInput.tsx
  src/features/bumpkins/components/Trade.tsx
  src/features/island/buildings/components/building/market/Crops.tsx
  src/features/world/ui/factions/emblemTrading/Trade.tsx
Labels: 📱 ux/ui

#4027 [FIX] Add withdraw restriction for Olive Royalty Shirt
  src/features/game/types/wearableValidation.ts
  src/features/game/types/withdrawables.ts
Labels: 🐞 bug

#3540 [FEAT] Russian dictionary
  index.html
  src/lib/i18n/dictionaries/dictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/utils/fonts.ts
  src/styles.css
Labels: 🌐 language

#4033 [FEAT] Play Testing Artefact Digging
  public/world/button.webp
  public/world/confirm_select.webp
  public/world/coral.webp
  public/world/crab.png
  public/world/crab.webp
  public/world/drill.png
  public/world/drill_select.webp
  public/world/pearl.webp
  public/world/pipi.webp
  public/world/pirate_bounty.webp
  public/world/sea_cucumber.png
  public/world/sea_cucumber.webp
  public/world/seaweed.webp
  public/world/select_box.png
  public/world/select_confirm_drill.webp
  public/world/select_confirm_lg.webp
  public/world/shovel.png
  public/world/shovel_select.webp
  public/world/starfish.webp
  src/features/game/lib/landDataStatic.ts
  src/features/world/containers/BumpkinContainer.ts
  src/features/world/scenes/BeachScene.ts
  src/features/world/ui/beach/DiggingMinigame.tsx
  src/lib/flags.ts
  src/lib/gameAnalytics.ts
  src/lib/utils/time.ts
Labels: ⭐ feature

#4036 [FIX] Rounding for Inventory Buy Panel
  src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
  src/features/world/ui/trader/BuyPanel.tsx
Labels: 🐞 bug

#4035 [FIX] Swap Bumpkin Silver and Gold Champion images
  src/features/game/types/images.ts
Labels: 🐞 bug

#4017 [FEAT] Pharaoh's Treasure Season Wearables
  metadata/metadata.ts
  public/wearables/000000000000000000000000000000000000000000000000000000000000015d.json
  public/wearables/000000000000000000000000000000000000000000000000000000000000015e.json
  public/wearables/000000000000000000000000000000000000000000000000000000000000015f.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000160.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000161.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000162.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000163.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000164.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000165.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000166.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000167.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000168.json
  public/wearables/349.json
  public/wearables/350.json
  public/wearables/351.json
  public/wearables/352.json
  public/wearables/353.json
  public/wearables/354.json
  public/wearables/355.json
  public/wearables/356.json
  public/wearables/357.json
  public/wearables/358.json
  public/wearables/359.json
  public/wearables/360.json
  src/features/game/types/bumpkin.ts
  src/features/game/types/withdrawables.test.ts
  src/features/game/types/withdrawables.ts
Labels: ⭐ Feature

#4039 [FEAT] Add faction pet boost
  src/features/game/events/landExpansion/feedBumpkin.test.ts
  src/features/game/expansion/lib/boosts.ts
  src/features/game/lib/factions.ts
  src/features/game/types/game.ts
  src/features/world/scenes/FactionHouseScene.ts
  src/features/world/ui/factions/FactionPetPanel.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4040 [FEAT] Update Pet Sleeping
  src/features/game/events/landExpansion/feedBumpkin.test.ts
  src/features/game/types/game.ts
  src/features/world/scenes/FactionHouseScene.ts
  src/features/world/ui/factions/FactionPetPanel.tsx
  src/lib/i18n/dictionaries/englishDictionary.ts
Labels: ⭐ Feature

#4018 [FEAT] Add faction teleport to map
  src/features/island/hud/components/deliveries/WorldMap.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: 📱 UI/UX

#4045 [FEAT] Trade island limits
  src/features/bumpkins/components/Trade.tsx
  src/features/game/components/VipAccess.tsx
  src/features/world/ui/trader/BuyPanel.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: 💸 Economy

#4038 [FEAT] Tomato & Lemon
  metadata/metadata.ts
  package.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000080.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000081.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000000d4.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000000d5.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000000d6.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000000d9.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000000fc.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000000ff.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000100.json
  public/erc1155/128.json
  public/erc1155/129.json
  public/erc1155/212.json
  public/erc1155/213.json
  public/erc1155/214.json
  public/erc1155/217.json
  public/erc1155/252.json
  public/erc1155/255.json
  public/erc1155/256.json
  public/erc1155/images/128.png
  public/erc1155/images/129.png
  public/erc1155/images/255.png
  public/erc1155/images/256.png
  src/assets/fruit/lemon/lemonSeed.webp
  src/assets/fruit/lemon/lemon_plant.webp
  src/assets/fruit/lemon/lemon_plant_ready.webp
  src/assets/fruit/tomato/tomato.webp
  src/assets/fruit/tomato/tomatoPlant.webp
  src/assets/fruit/tomato/tomatoPlantReady.webp
  src/assets/fruit/tomato/tomatoSeed.webp
  src/assets/resources/lemon.webp
  src/features/bumpkins/components/Trade.tsx
  src/features/game/lib/constants.test.ts
  src/features/game/lib/constants.ts
  src/features/game/lib/processEvent.ts
  src/features/game/types/fruits.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/withdrawables.ts
  src/features/island/buildings/components/building/market/Seeds.tsx
  src/features/island/fruit/FruitSeedling.tsx
  src/features/island/fruit/ReplenishedTree.tsx
  src/features/island/fruit/ReplenishingTree.tsx
  src/features/island/fruit/fruits.ts
  src/features/world/ui/trader/BuyPanel.tsx
  src/lib/flags.ts
  yarn.lock
Labels: ⭐ Feature

#4037 [FEAT] Seasonal Banner
  metadata/metadata.ts
  public/erc1155/00000000000000000000000000000000000000000000000000000000000002ea.json
  public/erc1155/00000000000000000000000000000000000000000000000000000000000002eb.json
  public/erc1155/746.json
  public/erc1155/747.json
  src/assets/decorations/banners/pharaohs_treasure_banner.webp
  src/features/game/components/modal/components/VIPItems.tsx
  src/features/game/events/landExpansion/bannerPurchased.test.ts
  src/features/game/events/landExpansion/bannerPurchased.ts
  src/features/game/lib/landDataStatic.ts
  src/features/game/lib/processEvent.ts
  src/features/game/types/collectibles.ts
  src/features/game/types/craftables.ts
  src/features/game/types/game.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/seasons.ts
  src/features/game/types/withdrawables.ts
  src/features/island/collectibles/CollectibleCollection.tsx
  src/features/island/collectibles/components/PharaohsTreasureBanner.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4044 [FEAT] Camel Onesie Boost
  metadata/metadata.ts
  public/wearables/000000000000000000000000000000000000000000000000000000000000015e.json
  public/wearables/350.json
  src/features/game/events/landExpansion/fruitHarvested.ts
  src/features/game/events/landExpansion/fruitPlanted.test.ts
  src/features/game/events/landExpansion/plantGreenhouse.test.ts
  src/features/game/types/bumpkinItemBuffs.ts
  src/features/game/types/removeables.ts
  src/features/game/types/wearableValidation.ts
  src/features/game/types/withdrawables.ts
Labels: ⭐ Feature

#4059 [FIX] Conditional display of bonusPrizeWeek label
  src/features/world/ui/factions/Champions.tsx
Labels: ⚙️ Chore

#4066 [CHORE] Simplify Faction Wearable Boost Code
  src/features/game/lib/factions.ts
Labels: ⚙️ Chore

#4067 [FIX] Ancient Rod Withdrawal Restriction
  src/features/game/types/removeables.ts
  src/features/game/types/wearableValidation.ts
Labels: 🐞 Bug

#4062 [FIX] Chores Crash when not in Faction
  src/features/island/hud/components/codex/pages/Chores.tsx
Labels: 🐞 Bug

#4061 [FIX] VIP Gift Opened Text
  src/features/world/ui/VIPGift.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: 🗒 Text Fix

#4058 [CHORE] Add New animation
  src/features/world/lib/animations.ts
Labels: 🚶‍♀️ Animation

#4056 [FEAT] Digging Resources
  metadata/metadata.ts
  src/assets/resources/camel_bone.webp
  src/assets/resources/cockle_shell.webp
  src/assets/resources/hieroglyph.webp
  src/assets/resources/sand.webp
  src/assets/resources/scarab.webp
  src/assets/resources/vase.webp
  src/features/game/types/desert.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/treasure.ts
  src/features/game/types/withdrawables.ts
  src/features/world/scenes/BeachScene.ts
  src/features/world/ui/beach/DiggingMinigame.tsx
Labels: ⭐ Feature

#4060 [FEAT] Beach Digging Play Testing Part 2
  public/world/camel_bone.webp
  public/world/cockle_shell.webp
  public/world/coral.webp
  public/world/crab.png
  public/world/crab.webp
  public/world/hieroglyph.webp
  public/world/old_bottle.png
  public/world/pearl.webp
  public/world/pipi.webp
  public/world/pirate_bounty.webp
  public/world/sand.webp
  public/world/scarab.webp
  public/world/sea_cucumber.png
  public/world/sea_cucumber.webp
  public/world/seaweed.webp
  public/world/shovel.png
  public/world/starfish.webp
  public/world/vase.webp
  public/world/wooden_compass.webp
  src/features/game/lib/constants.ts
  src/features/game/lib/transforms.ts
  src/features/game/types/game.ts
  src/features/world/containers/BumpkinContainer.ts
  src/features/world/scenes/BeachScene.ts
Labels: ⭐ Feature

#4051 [FEAT] Treasure Shop
  public/world/treasure_shop.png
  src/assets/map/beach.json
  src/features/game/events/landExpansion/craftCollectible.ts
  src/features/game/types/bumpkinActivity.ts
  src/features/game/types/collectibles.ts
  src/features/game/types/craftables.ts
  src/features/game/types/game.ts
  src/features/game/types/withdrawables.ts
  src/features/island/buildings/components/building/workBench/components/Tools.tsx
  src/features/world/scenes/BeachScene.ts
  src/features/world/ui/NPCModals.tsx
  src/features/world/ui/beach/treasure_shop/TreasureShop.tsx
  src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
  src/features/world/ui/beach/treasure_shop/TreasureShopCraft.tsx
  src/features/world/ui/beach/treasure_shop/TreasureShopSell.tsx
  src/features/world/ui/npcs/GoldTooth.tsx
  src/lib/npcs.ts
Labels: ⭐ Feature

#4057 [FEAT] Desert Rose
  metadata/metadata.ts
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000580.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000581.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000582.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000583.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000584.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000585.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000834.json
  public/erc1155/1408.json
  public/erc1155/1409.json
  public/erc1155/1410.json
  public/erc1155/1411.json
  public/erc1155/1412.json
  public/erc1155/1413.json
  public/erc1155/2100.json
  src/assets/sfts/desert_rose.webp
  src/features/game/events/landExpansion/harvestFlower.test.ts
  src/features/game/events/landExpansion/harvestFlower.ts
  src/features/game/lib/processEvent.ts
  src/features/game/types/collectibleItemBuffs.ts
  src/features/game/types/craftables.ts
  src/features/game/types/flowers.ts
  src/features/game/types/game.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/withdrawables.ts
  src/features/island/collectibles/CollectibleCollection.tsx
  src/features/island/collectibles/components/DesertRose.tsx
  src/features/island/flowers/FlowerBed.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4081 [FEAT] Aura
  metadata/metadata.ts
  public/wearables/000000000000000000000000000000000000000000000000000000000000016e.json
  public/wearables/000000000000000000000000000000000000000000000000000000000000016f.json
  public/wearables/366.json
  public/wearables/367.json
  public/wearables/images/366.png
  public/wearables/images/367.png
  src/assets/bumpkins/aura_silhoutte.png
  src/features/bumpkins/components/BumpkinEquip.tsx
  src/features/game/lib/bumpkinData.ts
  src/features/game/lib/landDataStatic.ts
  src/features/game/types/bumpkin.ts
  src/features/game/types/bumpkinPartSilhouettes.ts
  src/features/game/types/withdrawables.ts
  src/features/world/containers/BumpkinContainer.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
  src/lib/utils/tokenUriBuilder.ts
Labels: ⭐ Feature, 🚶‍♀️ Animation

#3925 [FEAT] Delivery Updates
  src/features/game/events/landExpansion/plantFlower.test.ts
  src/features/game/lib/bumpkinData.ts
  src/features/game/lib/landDataDynamic.ts
  src/features/game/lib/landDataStatic.ts
  src/features/island/delivery/components/Orders.tsx
  src/features/island/delivery/lib/delivery.ts
  src/features/world/scenes/PlazaScene.ts
  src/features/world/ui/NPCModals.tsx
  src/features/world/ui/deliveries/BumpkinDelivery.tsx
  src/features/world/ui/deliveries/dialogues.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
  src/lib/npcs.ts
Labels: ⭐ Feature

#4091 [FEAT] Crab Trap Boost Description
  metadata/metadata.ts
  public/wearables/00000000000000000000000000000000000000000000000000000000000000e6.json
  public/wearables/230.json
  src/features/game/types/bumpkinItemBuffs.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4089 [FEAT] Desert NPCS
  src/features/game/events/landExpansion/deliver.ts
  src/features/game/types/gifts.ts
  src/features/island/delivery/components/Orders.tsx
  src/features/island/delivery/lib/delivery.ts
  src/features/world/scenes/BeachScene.ts
  src/features/world/ui/NPCModals.tsx
  src/features/world/ui/deliveries/BumpkinDelivery.tsx
  src/features/world/ui/deliveries/dialogues.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
  src/lib/npcs.ts
Labels: ⭐ Feature

#4092 [FIX] Aura Sprite Bug
  src/features/world/containers/BumpkinContainer.ts
Labels: 🚶‍♀️ Animation

#4085 [FEAT] Pharaoh's Treasure Collectibles (1)
  metadata/metadata.ts
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000835.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000836.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000837.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000838.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000839.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083a.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083b.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083c.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083d.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083e.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083f.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000840.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000841.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000842.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000843.json
  public/erc1155/2101.json
  public/erc1155/2102.json
  public/erc1155/2103.json
  public/erc1155/2104.json
  public/erc1155/2105.json
  public/erc1155/2106.json
  public/erc1155/2107.json
  public/erc1155/2108.json
  public/erc1155/2109.json
  public/erc1155/2110.json
  public/erc1155/2111.json
  public/erc1155/2112.json
  public/erc1155/2113.json
  public/erc1155/2114.json
  public/erc1155/2115.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000170.json
  public/wearables/368.json
  src/assets/sfts/anubis_jackal.webp
  src/assets/sfts/pharaoh_gnome.webp
  src/assets/sfts/sarcophagus.webp
  src/assets/sfts/snake_in_jar.webp
  src/features/game/types/bumpkin.ts
  src/features/game/types/collectibles.ts
  src/features/game/types/craftables.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/withdrawables.ts
  src/features/island/collectibles/CollectibleCollection.tsx
  src/features/island/collectibles/components/Sarcophagus.tsx
  src/features/island/collectibles/components/template/Template.tsx
Labels: ⭐ Feature

#4083 [FEAT] Tomato Update
  src/features/game/events/landExpansion/sellCrop.test.ts
  src/features/game/expansion/components/LaTomatina.tsx
  src/features/game/expansion/components/Water.tsx
  src/features/game/expansion/lib/boosts.test.ts
  src/features/game/expansion/lib/boosts.ts
  src/features/game/types/specialEvents.ts
  src/features/island/buildings/components/building/market/Market.tsx
  src/features/island/hud/Hud.tsx
  src/features/island/hud/SpecialEventCountdown.tsx
  src/features/island/hud/WorldHud.tsx
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4107 [FEAT] Auction Wearables
  metadata/metadata.ts
  public/wearables/0000000000000000000000000000000000000000000000000000000000000170.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000171.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000172.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000173.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000174.json
  public/wearables/368.json
  public/wearables/369.json
  public/wearables/370.json
  public/wearables/371.json
  public/wearables/372.json
  public/wearables/images/368.png
  public/wearables/images/369.png
  public/wearables/images/370.png
  public/wearables/images/371.png
  public/wearables/images/372.png
  src/features/game/types/bumpkin.ts
  src/features/game/types/bumpkinItemBuffs.ts
  src/features/game/types/withdrawables.ts
Labels: ⭐ Feature

#4108 [FEAT] Auction Collectibles
  metadata/metadata.ts
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000842.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000848.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000849.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000084a.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000084b.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000084c.json
  public/erc1155/2114.json
  public/erc1155/2120.json
  public/erc1155/2121.json
  public/erc1155/2122.json
  public/erc1155/2123.json
  public/erc1155/2124.json
  src/assets/sfts/lemon_tea_bath.webp
  src/assets/sfts/pyramid.webp
  src/assets/sfts/tomato_clown.gif
  src/features/game/types/collectibleItemBuffs.ts
  src/features/game/types/collectibles.ts
  src/features/game/types/craftables.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/withdrawables.ts
  src/features/island/collectibles/CollectibleCollection.tsx
  src/features/island/collectibles/components/LemonTeaBath.tsx
  src/features/island/collectibles/components/Pyramid.tsx
  src/features/island/collectibles/components/TomatoClown.tsx
Labels: ⭐ Feature

#4115 [FEAT] Pharaoh's Treasure Assets (1)
  metadata/metadata.ts
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000835.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000836.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000837.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000838.json
  public/erc1155/000000000000000000000000000000000000000000000000000000000000083a.json
  public/erc1155/2101.json
  public/erc1155/2102.json
  public/erc1155/2103.json
  public/erc1155/2104.json
  public/erc1155/2106.json
  public/erc1155/images/2101.png
  public/erc1155/images/2102.png
  public/erc1155/images/2103.png
  public/erc1155/images/2104.png
  public/erc1155/images/2106.png
  public/erc1155/images/3x3_bg 1920x1920.png
  src/assets/sfts/duamutef.webp
  src/assets/sfts/hapy.webp
  src/assets/sfts/imsety.webp
  src/assets/sfts/oasis.webp
  src/assets/sfts/qebehsenuef.webp
  src/features/game/types/craftables.ts
  src/features/game/types/images.ts
  src/features/island/collectibles/CollectibleCollection.tsx
  src/features/island/collectibles/components/LemonTeaBath.tsx
  src/features/island/collectibles/components/Pyramid.tsx
  src/features/island/collectibles/components/Sarcophagus.tsx
  src/features/island/collectibles/components/TomatoClown.tsx
  src/features/island/collectibles/components/template/ImageStyle.tsx
Labels: ⭐ Feature

#4127 [FEAT] Pharaoh's Treasure auction item boosts
  src/features/game/events/landExpansion/drillOilReserve.test.ts
  src/features/game/events/landExpansion/drillOilReserve.ts
  src/features/game/events/landExpansion/fruitHarvested.test.ts
  src/features/game/events/landExpansion/fruitHarvested.ts
  src/features/game/events/landExpansion/fruitPlanted.test.ts
  src/features/game/events/landExpansion/fruitPlanted.ts
  src/features/game/events/landExpansion/plant.ts
  src/features/game/events/landExpansion/plantGreenhouse.test.ts
  src/features/game/events/landExpansion/plantGreenhouse.ts
  src/features/game/types/bumpkinItemBuffs.ts
  src/features/game/types/collectibleItemBuffs.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature

#4132 [FEAT] Update select boxes
  public/world/confirm_select.webp
  public/world/drill_confirm.webp
  public/world/drill_select.webp
  public/world/drill_select_sm.webp
  public/world/pearl.webp
  public/world/pipi.webp
  public/world/select_confirm_sm.webp
  public/world/shovel_select.webp
  public/world/shovel_select_sm.webp
  src/features/game/types/images.ts
  src/features/world/scenes/BeachScene.ts
Labels: ⭐ Feature

#4134 [FEAT] Fossil Head
  metadata/metadata.ts
  public/wearables/0000000000000000000000000000000000000000000000000000000000000176.json
  public/wearables/0000000000000000000000000000000000000000000000000000000000000177.json
  public/wearables/374.json
  public/wearables/375.json
  public/wearables/images/375.png
  src/features/game/types/bumpkin.ts
  src/features/game/types/withdrawables.ts
Labels: ⭐ Feature

#4144 [FEAT] Withdrawal Restrictions for Auction Items
  src/features/game/types/removeables.ts
  src/features/game/types/wearableValidation.ts
  src/features/game/types/withdrawables.ts
Labels: ⭐ Feature

#4145 [FEAT] Dig SFX + Move Digs Hud UI
  src/assets/sound-effects/soundEffects.ts
  src/features/island/hud/components/DesertDiggingDisplay.tsx
  src/features/pumpkinPlaza/components/ChatUI.tsx
  src/features/world/containers/BumpkinContainer.ts
  src/features/world/scenes/BeachScene.ts
  src/features/world/scenes/Preloader.ts
  src/lib/flags.ts
Labels: 🔉 Sound, 📱 UI/UX

#4136 [FEAT] Tomato Bombard & Cannonball
  metadata/metadata.ts
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000839.json
  public/erc1155/0000000000000000000000000000000000000000000000000000000000000850.json
  public/erc1155/2105.json
  public/erc1155/2128.json
  public/world/tomato_bombard.gif
  src/assets/sfts/cannonball.webp
  src/assets/sfts/tomato_bombard.gif
  src/assets/sfts/tomato_bombard_click.png
  src/assets/sfts/tomato_bombard_idle.png
  src/features/game/events/landExpansion/fruitHarvested.test.ts
  src/features/game/events/landExpansion/fruitHarvested.ts
  src/features/game/events/landExpansion/fruitPlanted.test.ts
  src/features/game/events/landExpansion/fruitPlanted.ts
  src/features/game/lib/processEvent.ts
  src/features/game/types/collectibleItemBuffs.ts
  src/features/game/types/collectibles.ts
  src/features/game/types/craftables.ts
  src/features/game/types/images.ts
  src/features/game/types/index.ts
  src/features/game/types/removeables.ts
  src/features/game/types/withdrawables.ts
  src/features/island/collectibles/CollectibleCollection.tsx
  src/features/island/collectibles/components/TomatoBombard.tsx
  src/features/world/scenes/PlazaScene.ts
  src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
  src/lib/i18n/dictionaries/englishDictionary.ts
  src/lib/i18n/dictionaries/frenchDictionary.ts
  src/lib/i18n/dictionaries/portugueseDictionary.ts
  src/lib/i18n/dictionaries/russianDictionary.ts
  src/lib/i18n/dictionaries/turkishDictionary.ts
  src/lib/i18n/dictionaries/types.ts
Labels: ⭐ Feature
